export const GET_INIT_LOGS = "GET_INIT_LOGS";
export const SET_FOOD_SEARCH_ITEM = "SET_FOOD_SEARCH_ITEM";
export const SET_FOOD_ENTRY_DATA = "SET_FOOD_ENTRY_DATA";
export const SET_FOOD_ENTRY = "SET_FOOD_ENTRY";
export const CLEAR_FOOD_ENTRY_DATA = "CLEAR_FOOD_ENTRY_DATA";
export const ADD_TO_MEALS = "ADD_TO_MEALS";
export const REMOVE_FROM_MEALS = "REMOVE_FROM_MEALS";